# Write a program to display sum of odd numbers and even numbers separately that fall between two
# numbers accepted from the user.(including both numbers) 100 and 500.



# n1=int(input("enter the number"))
# n2=int(input("enter the second number"))
# i=n1
# sum1=0
# sum2=0
# while i<=n2:
#     if i%2==0:
#         sum1=sum1+i
#     else:
#         sum2=sum2+i
#     i=i+1
# print("even numbers",sum1)
# print("odd numbers",sum2)
    






