#   *
#  ***
# *****
#  ***
#   *


# a=1
# i=1
# while i<=3:
#     b=1
#     while b<=3-i:
#         print(" ",end=" ")
#         b=b+1
#     j=1
#     while j<=a:
#         print("*",end=" ")
#         j=j+1
#     print()
#     a=a+2
#     i=i+1
# a=3
# i=3
# while i>=1:
#     b=1
#     while b<=4-i:
#         print(" ",end=" ")
#         b=b+1
#     j=1
#     while j<=a:
#         print("*",end=" ")
#         j=j+1
#     print()
#     i=i-1
#     a=a-2

# i=1
# while i<=5:
#     j=1
#     while j<=5:
#         if i+j==4 or i-j==2 or i+j==8 or j-i==2:
#             print("*",end=" ")
#         else:
#             print(" ",end=" ")
#         j=j+1
#     print()
#     i=i+1

# i=1
# while i<=5:
#     j=1
#     while j<=5-i:
#         print(" ",end=" ")
#         j=j+1
#     k=i
#     while k>0:
#         print(k,end=" ")
#         k=k-1
#     a=2
#     while a<=i:
#         print(a,end=" ")
#         a=a+1
#     print()
#     i=i+1


# i=5
# while i>=1:
#     b=1
#     while b<=5-i:
#         print("",end="")
#         b=b+1
#     j=1
#     while j<=i:
#         print(j,end=" ")
#         j=j+1
#     print()
#     i=i-1
       

