# for i in range (5):
#     print(i)       
#op=  0
#     1
#     2
#     3
#     4

# for i in (1,2,3):
#     print(i)
#     op=1

# for i in  (2,3,4):
#     print("i")
#op=i
#   i
#   i

# for i in(4,3,2,1,0):
#     print(i,end="")
# op=43210



# for i in range(10):
#     if i%2!=0:
#         print(i,"hello")
# op =1 hello
#    3 hello 
#    5 hello 
#    7 hello 
#    9 hello 

# for i in (10):
#     if i%2!=0:
#         print(i,"hello")
# op= type error


# for i in range(10,2,-2):
#     print(i,"hello")
# op=10 hello 
#     8 hello 
#     6 hello 
#     4 hello

# str="python output based questions"
# word=str.split()
# for i in word:
# op= syntax error 


# for i in range(7,10):
#     print("Python Output based Questions")
# print("Python Output based Questions")
# op=python output based questions
#    ------------------------------
#    -------------------------------
#    ------------------------------4 times


# for i in range(7,-2,-9):
#     for j in range(i):
#      print(j)
# op=1
#    2
#    3
#    4
#    5
#    6

# for i in range(7,-2,-9):
#     print(i)
# op= 7

# for i in range (1,7):
#     i=i+2
#     print(i)
# 
# while(i<10):
#  i=i+3
#  print(i)


# for i in range(i=44,7):
#     print("Hello",i)
#     i=i+3


# for i in range(20):
#     if i//4==0:
#         print(i)  

# x=1234
# while x%10:
#     x=x//10
#     print(x)

# f

# 

# p=10
# q=20
# p=p*q//4
# q=p+q**3
# print(p,q)

# x=2
# y=6
# x=x+y/2 + y//4
# print(x)

# n=11
# for i in range(2,n//2):
#  if n%i!=0: 
#     print("Python Output based Questions")
#     break
# else:
#     print("Bye")

# n=20
# for i in range(2,n//4):
#   if n%i==0:
#     print("Python Output based Questions")
#   else:
#     print("Bye")

# for i in range (123):
#   print(i)

# for i in [10,20,30]:
#   print("Hello",i)

# x=2
# for i in range(x**2,x,-1):
#   print(x)

# x=10
# for i in range(x):
#     if x==5:
#         break
#         print ("H")
#     print("x")

# x=6
# for i in range(x):
#  if x==5:
#    break
#  print("H")
# print(x)


# from re import S


# s=0
# for i in range (5):
#     s=s+i
#     print(s)


# for i in range(1,11):
#    print("%d"%i)

# print((3>1) and (9<1))




