# n=int(input("enter the number"))
# i=1
# sum=0
# while i<=1:
#     a=n%10
#     b=n//10%10
#     c=n//100%10
#     sum=a+b+c
#     i=i+1
#     if sum%n:
#         print("it is harshad number")
#     else:
#         print("it is not harshad number")

# a=int(input("enter the number:-"))
# n=a
# sum=0
# while a>0:
#     sum=sum+a%10
#     a=a//10
# if n%sum==0:
#         print("yes")
# else:
#         print("no")          



# a=int(input("enter the number"))
# i=0
# sum=0
# n=a
# while a>0:
#     i=a%10
#     sum=sum+i
#     a=a//10
# if n%sum==0:
#         print(sum,"it is harshad number")
# else:
#         print(sum,"it is not harshad number")




















