# *
# **
# ***
# ****
# ***** 

# i=1
# while i<=5:
#     j=1
#     while j<=i:
#         print("*",end="")
#         j=j+1
#     print()
#     i=i+1

# 1
# 12
# 123
# 1234
# 12345

# i=1
# while i<=5:
#     j=1
#     while j<=i:
#         print(j,end="")
#         j=j+1
#     print()
#     i=i+1


# 1
# 22
# 333
# 4444
# 55555

# i=1
# while i<=5:
#     j=1
#     while j<=i:
#         print(i,end="")
#         j=j+1
#     print()
#     i=i+1

#54321
# 5432
# 543
# 54
# 5

# i=1
# while i<=5:
#     j=5
#     while j>=i:
#         print(j,end="")
#         j=j-1
#     print()
#     i=i+1

#*****
# ****
# ***
# **
# *

# i=1
# while i<=5:
#     j=5
#     while j>=i:
#         print("*",end="")
#         j=j-1
#     print()
#     i=i+1


#55555
# 4444
# 333
# 22
# 1


# i=5
# while i>=1:
#     j=1
#     while j<=i:
#         print(i,end="")
#         j=j+1
#     print()
#     i=i-1

# 5
# 54
# 543
# 5432
# 54321

# i=5
# while i>=1:
#     j=5
#     while j>=i:
#         print(j,end="")
#         j=j-1
#     print()
#     i=i-1

# 5
# 44
# 333
# 2222
# 11111

# i=5
# while i>=1:
#     j=5
#     while j>=i:
#         print(i,end="")
#         j=j-1
#     print()
#     i=i-1

# 12345
# 1234
# 123
# 12
# 1

# i=5
# while i>=1:
#     j=1
#     while j<=i:
#         print(j,end="")
#         j=j+1
#     print()
#     i=i-1

# 55555
# 4444
# 333
# 22
# 1

# i=5
# while i>=1:
#     j=1
#     while j<=i:
#         print(i,end="")
#         j=j+1
#     print()
#     i=i-1


# 1
# 2 3
# 4 5 6
# 7 8 9 10

# i=1
# a=1
# while i<=4:
#     j=1
#     while j<=i:
#         print(a,end="")
#         j=j+1
#         a=a+1
#     print()
#     i=i+1

# 0
# 0 1
# 0 2 4
# 0 3 6 9
# 0 4 8 12 16
# 0 5 10 15 20 25

# i=0
# while i<=5:
#     j=0
#     while j<=i:
#         print(j*i,end=" ")
#         j=j+1
#     print()
#     i=i+1

# 0
# 01
# 012
# 0123
# 01234

# i=0
# while i<5:
#     j=0
#     while j<=i:
#         print(j,end="")
#         j=j+1
#     print()
#     i=i+1


# 0
# 11
# 222
# 3333
# 44444


# i=0
# while i<5:
#     j=0
#     while j<=i:
#         print(i,end="")
#         j=j+1
#     print()
#     i=i+1


# 1 2 3 4 5 6 7 8 9 10
# ----------------------
#-----------------------
# 10 20 30 40 50 60 70 80 90 100
# i=1
# while i<=10:
#     j=1
#     while j<=10:
#         print(j*i,end=" ")
#         j=j+1
#     print()
#     i=i+1

# n1=int(input("enter the number"))
# n2=int(input("enter second number"))
# i=n1
# while i<=n2:
#     j=1
#     while j<=10:
#         print(i,"*",j,"=",j*i)
#         j=j+1
#     print()
#     i=i+1


# n1=int(input("enter the number"))
# n2=int(input("enter the number"))
# i=n1
# while i<=n2:
#     j=1
#     while j<=n2:
#         print(i,"*",j,"=",i*j)
#         j=j+1
#     break

# i=1
# while i<=30:
#     if i%2!=0 and i%3!=0 and i%5!=0:
#         print(i,"prime")
#     elif  i==2 or i==3 or i==5:
#         print(i,"prime")
#     else:
#         print(i,"not prime") 
#     i=i+1           




# 1*1=1--------------10*1=10
# 1*2=2--------------10*2=20
# --------------------------
#--------------------------
# 1*10=10------------10*10=100


# i=1
# while i<=10:
#     j=1
#     while j<=10:
#         print(j,"*",i,"=",j*i)
#         j=j+1
#     print()
#     i=i+1


# p
# py
# pyt
# pyth
# pytho
# python

# string=input("enter any string")
# i=0
# while i<len(string):
#     j=0
#     while j<=i:
#         print(string[j],end="")
#         j=j+1
#     print()
#     i=i+1

# p
# yy
# ttt
# hhhh
# ooooo
# nnnnnn

# string=input("enter any string")
# i=0
# while i<len(string):
#     j=0
#     while j<=i:
#         print(string[i],end="")
#         j=j+1
#     print()
#     i=i+1

#     *
#    **
#   ***
#  ****
# *****
# i=1
# while i<=5:
#     b=1
#     while b<=5-i:
#         print("_",end="")
#         b=b+1
#     j=1
#     while j<=i:
#         print("*",end="")
#         j=j+1
#     print()
#     i=i+1

#    1
#   12
#  123
# 1234
#12345

# i=1
# while i<=5:
#     b=1
#     while b<=5-i:
#         print("_",end="")
#         b=b+1
#     j=1
#     while j<=i:
#         print(j,end="")
#         j=j+1
#     print()
#     i=i+1

#      1
#     22
#    333
#   4444
#  55555


# i=1
# while i<=5:
#     b=1
#     while b<=5-i:
#         print("_",end="")
#         b=b+1
#     j=1
#     while j<=i:
#         print(i,end="")
#         j=j+1
#     print()
#     i=i+1


#     *
#    ***
#   *****
#  *******
#  *********
# k=1
# i=1
# while i<=5:
#     b=1
#     while b<=5-i:
#         print("_",end="")
#         b=b+1
#     j=1
#     while j<=k:
#         print("*",end="")
#         j=j+1
#     k=k+2
#     print()
#     i=i+1

#     1
#    123
#   12345
#  1234567
# 123456789

# k=1
# i=1
# while i<=5:
#     b=1
#     while b<=5-i:
#         print("_",end="")
#         b=b+1
#     j=1
#     while j<=k:
#         print(j,end="")
#         j=j+1
#     k=k+2
#     print()
#     i=i+1

#        1
#       222
#      33333
#     4444444
 #   555555555

# k=1
# i=1
# while i<=5:
#     b=1
#     while b<=5-i:
#         print("_",end="")
#         b=b+1
#     j=1
#     while j<=k:
#         print(i,end="")
#         j=j+1
#     k=k+2
#     print()
#     i=i+1


#      1
#     333
#    55555
#   7777777
#  999999999

# k=1
# i=1
# while i<=5:
#     b=1
#     while b<=5-i:
#         print("_",end="")
#         b=b+1
#     j=1
#     while j<=k:
#         print(k,end="")
#         j=j+1
#     k=k+2
#     print()
#     i=i+1

# from re import I


# i=1
# while i<=50:
#     if i%5!=0:
#         print(i)
#         if i%5==0:
#             continue
#         i=i+1
# i=1
# while i<=50:
#     if i%5!=0:
#         print(i)   
#     i=i+1    


# i=1
# while i<=5:
#     j=5
#     while j>i:
#         print(" ",end="")
#         j=j-1
#     k=0
#     while k<i:
#         print(k**2,end=" ")
#         k=k+1
#     print()
#     i=i+1

# i=1
# while i<=5:
#     j=1
#     while j<=i:
#         print(i**2,end="")
#         j=j+1
#     print()
#     i=i+1

# i=1
# k=0
# while i<=5:
#     j=1
#     while j<=i:
#            print(i*j,end=" ")
#            j=j+1
#     print()
#     i=i+1
#     k=k+1



# a=int(input("enter the number:-"))
# b=0
# i=1
# while i<=a:
#     if a%i==0:
#         b=b+1
#     i=i+1
# if b==2:
#     print("it is a prime ")
# else:
#     print("it is not prime")       


# n=int(input("enter the number"))
# name=(input("enter the number"))
# i=1
# while i<=n:
#     print(name)
#     i=i+1

# 1 to 100

# i=1
# while i<=10:
#     j=i
#     while j<=100:
#         print(j,end=" ")
#         j=j+10
#     print()
#     i=i+1